modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="create_fatals_qol_crafting"
version="1.0.0"
displayName="Create: Fatal's QoL Crafting"
displayURL="https://fatalmistake02.com"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="FatalMIstake02"
description="Adds compatibility between Fatal\u2019s QoL Crafting and Create"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_fatals_qol_crafting]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_fatals_qol_crafting]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_fatals_qol_crafting]]
    modId="fatals_qol_crafting"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_fatals_qol_crafting]]
    modId="create"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration